spring.application.name=artbackend
server.port = 8083

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/art_gallery_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=akshayaumesh20
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Data Initialization
spring.sql.init.mode=always

# Security Configuration
spring.security.user.name=admin
spring.security.user.password=admin123

# Increase upload size for high-res art images
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-http-form-post-size=50MB

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=akshayaputti21@gmail.com
spring.mail.password=zljheddwrdtucliv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.debug=true
spring.mail.properties.mail.smtp.ssl.trust=*
